# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 22:57
from __future__ import unicode_literals

#import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
from django.contrib.gis.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallesGeocod',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('alt_i', models.IntegerField(blank=True, null=True)),
                ('alt_f', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.PointField(blank=True, null=True, srid=4326)),
                ('rango', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'calles_geocod',
            },
        ),
    ]
