# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 23:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0002_auto_20170219_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='callesgeocod',
            name='geom_3857',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=3857),
        ),
    ]
